### ISSUE TITLE
`pruneNetworksWithRetry` sometimes gets in an infinite loop

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/interchaintest#532]
We see this in some of our test cases:

```logs
=== RUN   TestPacketForwardMiddleware
    setup.go:226: Failed to prune networks during docker cleanup: All attempts fail:
        #1: Error response from daemon: a prune operation is already running
        #2: Error response from daemon: a prune operation is already running
        #3: Error response from daemon: a prune operation is already running
        #4: Error response from daemon: a prune operation is already running
        #5: Error response from daemon: a prune operation is already running
        #6: Error response from daemon: a prune operation is already running
        #7: Error response from daemon: a prune operation is already running
        #8: Error response from daemon: a prune operation is already running
        #9: Error response from daemon: a prune operation is already running
        #10: Error response from daemon: a prune operation is already running
panic: test timed out after 30m0s

goroutine 24 [running]:
testing.(*M).startAlarm.func1()
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:2036 +0xbb
created by time.goFunc
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive, 30 minutes]:
testing.(*T).Run(0xc0002c5a00, {0x39be285, 0x1b}, 0x418b400)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1494 +0x789
testing.runTests.func1(0x0?)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1846 +0x9a
testing.tRunner(0xc0002c5a00, 0xc000b11ba0)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1446 +0x217
testing.runTests(0xc0001bd040?, {0x6962fc0, 0x4, 0x4}, {0x40?, 0x7f011aa92498?, 0x698ac80?})
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1844 +0x7ed
testing.(*M).Run(0xc0001bd040)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1726 +0xa85
main.main()
	_testmain.go:55 +0x2ea

goroutine 23 [select, 30 minutes]:
github.com/desertbit/timer.timerRoutine()
	/home/strangelove/go/pkg/mod/github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:119 +0x18b
created by github.com/desertbit/timer.init.0
	/home/strangelove/go/pkg/mod/github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:15 +0x2a

goroutine 10 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0002be380)
	/home/strangelove/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x185
created by go.opencensus.io/stats/view.init.0
	/home/strangelove/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0xf7

goroutine [12](https://github.com/strangelove-ventures/interchaintest/actions/runs/4811558337/jobs/8565696970#step:5:13) [chan receive, 30 minutes]:
testing.(*T).Parallel(0xc0002c5ba0)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1271 +0x4f3
github.com/strangelove-ventures/interchaintest/v7/examples/ibc.TestInterchainAccounts(0xc0002c5ba0)
	/home/strangelove/actions-runner/_work/interchaintest/interchaintest/examples/ibc/interchain_accounts_test.go:30 +0x128
testing.tRunner(0xc0002c5ba0, 0x418b3e8)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1493 +0x75e

goroutine [13](https://github.com/strangelove-ventures/interchaintest/actions/runs/4811558337/jobs/8565696970#step:5:14) [chan receive, 30 minutes]:
testing.(*T).Parallel(0xc00054e340)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1271 +0x4f3
github.com/strangelove-ventures/interchaintest/v7/examples/ibc_test.TestInterchainQueries(0xc00054e340)
	/home/strangelove/actions-runner/_work/interchaintest/interchaintest/examples/ibc/interchain_queries_test.go:30 +0x11b
testing.tRunner(0xc00054e340, 0x418b3f0)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:[14](https://github.com/strangelove-ventures/interchaintest/actions/runs/4811558337/jobs/8565696970#step:5:15)46 +0x217
created by testing.(*T).Run
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1493 +0x75e

goroutine 14 [chan receive, 30 minutes]:
testing.(*T).Parallel(0xc0000aa9c0)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1271 +0x4f3
github.com/strangelove-ventures/interchaintest/v7/examples/ibc_test.TestLearn(0xc0000aa9c0)
	/home/strangelove/actions-runner/_work/interchaintest/interchaintest/examples/ibc/learn_ibc_test.go:24 +0x11b
testing.tRunner(0xc0000aa9c0, 0x418b3f8)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1493 +0x75e

goroutine [15](https://github.com/strangelove-ventures/interchaintest/actions/runs/4811558337/jobs/8565696970#step:5:16) [select, 30 minutes]:
net/http.(*persistConn).roundTrip(0xc0004e99e0, 0xc0005de140)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/http/transport.go:2620 +0x104a
net/http.(*Transport).roundTrip(0xc00039db80, 0xc0005fa000)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/http/transport.go:595 +0xd7e
net/http.(*Transport).RoundTrip(0xc0005fa000?, 0x5445940?)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/http/roundtrip.go:17 +0x37
net/http.send(0xc0005fa000, {0x5445940, 0xc00039db80}, {0x0?, 0x48ba80?, 0x0?})
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/http/client.go:251 +0x943
net/http.(*Client).send(0xc0001ded50, 0xc0005fa000, {0x0?, 0x0?, 0x0?})
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/http/client.go:175 +0x[16](https://github.com/strangelove-ventures/interchaintest/actions/runs/4811558337/jobs/8565696970#step:5:17)5
net/http.(*Client).do(0xc0001ded50, 0xc0005fa000)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/http/client.go:715 +0x10c9
net/http.(*Client).Do(...)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/http/client.go:581
github.com/docker/docker/client.(*Client).doRequest(0xc0002be780, {0x5463690, 0xc0000560b8}, 0xc000211800)
	/home/strangelove/go/pkg/mod/github.com/docker/docker@v20.10.19+incompatible/client/request.go:125 +0x1fb
github.com/docker/docker/client.(*Client).sendRequest(0x0?, {0x5463690, 0xc0000560b8}, {0x3988047, 0x4}, {0x399cd8c, 0x10}, 0x431b30?, {0x543f1a0, 0xc0005e4120}, ...)
	/home/strangelove/go/pkg/mod/github.com/docker/docker@v20.10.19+incompatible/client/request.go:113 +0x1[17](https://github.com/strangelove-ventures/interchaintest/actions/runs/4811558337/jobs/8565696970#step:5:18)
github.com/docker/docker/client.(*Client).post(0x370a160?, {0x5463690, 0xc0000560b8}, {0x399cd8c, 0x10}, 0x4abc65?, {0x370a160, 0xc0003d2000}, 0xc00058cc58?)
	/home/strangelove/go/pkg/mod/github.com/docker/docker@v20.10.19+incompatible/client/request.go:46 +0x16e
github.com/docker/docker/client.(*Client).NetworkCreate(0xc0000aaea0?, {0x5463690, 0xc0000560b8}, {0xc0003129a8, 0x17}, {0x1, {0x0, 0x0}, {0x0, 0x0}, ...})
	/home/strangelove/go/pkg/mod/github.com/docker/docker@v20.10.19+incompatible/client/network_create.go:17 +0x205
github.com/strangelove-ventures/interchaintest/v7/internal/dockerutil.DockerSetup({0x5467a60, 0xc0000aaea0})
	/home/strangelove/actions-runner/_work/interchaintest/interchaintest/internal/dockerutil/setup.go:79 +0x2c7
github.com/strangelove-ventures/interchaintest/v7.DockerSetup(0xc0000aaea0)
	/home/strangelove/actions-runner/_work/interchaintest/interchaintest/test_setup.go:38 +0x45
github.com/strangelove-ventures/interchaintest/v7/examples/ibc_test.TestPacketForwardMiddleware(0xc0000aaea0)
	/home/strangelove/actions-runner/_work/interchaintest/interchaintest/examples/ibc/packet_forward_test.go:38 +0x11b
testing.tRunner(0xc0000aaea0, 0x4[18](https://github.com/strangelove-ventures/interchaintest/actions/runs/4811558337/jobs/8565696970#step:5:19)b400)
	/home/strangelove/actions-runner/_work/_tool/go/1.[19](https://github.com/strangelove-ventures/interchaintest/actions/runs/4811558337/jobs/8565696970#step:5:20).7/x64/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/testing/testing.go:1493 +0x75e

goroutine 50 [IO wait, 30 minutes]:
internal/poll.runtime_pollWait(0x7f011aad0958, 0x72)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc0002be918, 0xc0005bb000?, 0x0)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0xbd
internal/poll.(*pollDesc).waitRead(...)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0002be900, {0xc0005bb000, 0x1000, 0x1000})
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/internal/poll/fd_unix.go:167 +0x415
net.(*netFD).Read(0xc0002be900, {0xc0005bb000, 0x1000, 0x1000})
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/fd_posix.go:55 +0x51
net.(*conn).Read(0xc000314828, {0xc0005bb000, 0x1000, 0x1000})
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/net.go:183 +0xb1
net/http.(*persistConn).Read(0xc0004e99e0, {0xc0005bb000, 0x1000, 0x1000})
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/http/transport.go:1929 +0x105
bufio.(*Reader).fill(0xc0001daf60)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/bufio/bufio.go:106 +0x2ab
bufio.(*Reader).Peek(0xc0001daf60, 0x1)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/bufio/bufio.go:144 +0xd2
net/http.(*persistConn).readLoop(0xc0004e99e0)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/http/transport.go:[20](https://github.com/strangelove-ventures/interchaintest/actions/runs/4811558337/jobs/8565696970#step:5:21)93 +0x2c8
created by net/http.(*Transport).dialConn
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/http/transport.go:1751 +0x2586

goroutine 51 [select, 30 minutes]:
net/http.(*persistConn).writeLoop(0xc0004e99e0)
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/http/transport.go:[23](https://github.com/strangelove-ventures/interchaintest/actions/runs/4811558337/jobs/8565696970#step:5:24)92 +0x1a9
created by net/http.(*Transport).dialConn
	/home/strangelove/actions-runner/_work/_tool/go/1.19.7/x64/src/net/http/transport.go:1752 +0x[26](https://github.com/strangelove-ventures/interchaintest/actions/runs/4811558337/jobs/8565696970#step:5:27)1a
FAIL	github.com/strangelove-ventures/interchaintest/v7/examples/ibc	1800.[40](https://github.com/strangelove-ventures/interchaintest/actions/runs/4811558337/jobs/8565696970#step:5:41)6s
```

**Comment by jonathanpberger** [comment]
@agouin sez "we need to look into the test runner. Maybe one or two of the three are in a bad state (and round-robin shunts you to a good one after a few retries?)

**Comment by jonathanpberger** [comment]
to check: 

shell in
check state of docker
check state of GH actions service
journal will capture all these logs

**Comment by boojamya** [comment]
Since updating docker (https://github.com/strangelove-ventures/interchaintest/pull/593), I have not seen this pruning error. 
Closing.
